# Generated by Django 4.1.3 on 2023-04-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_schedule_doctor_remove_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sch',
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
