# Generated by Django 4.1.3 on 2023-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_doctor_schedule_remove_schedule_sch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('email', 'phone')},
        ),
    ]
