# Generated by Django 4.1.3 on 2023-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_doctor_options_alter_doctor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
